Repository chris-greening/instascrape, pull requests merged in 2020-10, with the labels that each got.

#22 included chromedrivers, included max_liked_post example, added new pa…
  examples/max_liked_post.ipynb
  examples/profile_scrape/dynamic_profile.py
  requirements.txt
Labels: examples, hacktoberfest-accepted

#25 Update README with minimum python version information
  README.md
Labels: documentation, hacktoberfest-accepted

#26 Fix docstrings and typing
  instascrape/scrapers/hashtag.py
  instascrape/scrapers/http_error_page.py
  instascrape/scrapers/landing_page.py
  instascrape/scrapers/login_page.py
  instascrape/scrapers/post.py
  instascrape/scrapers/profile.py
  instascrape/scrapers/static_scraper.py
Labels: hacktoberfest-accepted

#28 Massive redesign
  examples/README.md
  instascrape/__init__.py
  instascrape/core/__init__.py
  instascrape/core/_json_engine.py
  instascrape/core/_mappings.py
  instascrape/core/_static_scraper.py
  instascrape/exceptions/exceptions.py
  instascrape/instascrape.py
  instascrape/scrapers/__init__.py
  instascrape/scrapers/hashtag.py
  instascrape/scrapers/http_error_page.py
  instascrape/scrapers/json_scraper.py
  instascrape/scrapers/landing_page.py
  instascrape/scrapers/login.py
  instascrape/scrapers/login_page.py
  instascrape/scrapers/post.py
  instascrape/scrapers/profile.py
  instascrape/scrapers/static_scraper.py
  instascrape/tools/__init__.py
  instascrape/tools/parsers.py
  tests/test_hashtag.py
  tests/test_login.py
  tests/test_post.py
  tests/test_profile.py
Labels: breaking-change, enhancement, hacktoberfest-accepted

#30 Fix examples
  examples/instagram_to_csv/instascrape_csv_example.ipynb
  examples/instagram_to_csv/instascrape_csv_example.py
  examples/profile_scrape/dynamic_profile.py
  examples/profile_scrape/profile_scraper.ipynb
  examples/simple_hashtag_comparison/simple_hashtag_comparison.ipynb
  requirements.txt
Labels: examples, hacktoberfest-accepted

#32 Json flattener
  instascrape/core/_json_flattener.py
  instascrape/core/_mappings.py
  instascrape/core/_static_scraper.py
  instascrape/scrapers/json_scraper.py
  setup.py
  tests/scrapers/test_post.py
Labels: enhancement, hacktoberfest-accepted
